spring.application.name=taskmanagerapp
spring.datasource.url=jdbc:mysql://localhost:3306/taskmanagerapp
spring.datasource.username=root
spring.datasource.password=1707
server.port=7000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true